-- JWTトークン用テーブル作成及びテストデータ投入
CREATE TABLE `TOKEN_INFO` (
  `TOKEN_ID` varchar(100) NOT NULL,
  `TOKEN` text NOT NULL,
  `CREATE_PRG` text NOT NULL,
  `CREATE_DATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_PRG` text NOT NULL,
  `UPDATE_DATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`TOKEN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `TOKEN_INFO` (`TOKEN_ID`, `TOKEN`, `CREATE_PRG`, `CREATE_DATE_TIME`, `UPDATE_PRG`, `UPDATE_DATE_TIME`) VALUES
('1c097be54e414b689c9ecfef8ba77086', 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0a3lzbjEwMjhAZ21haWwuY29tIiwiaXNzIjoiY29tLnNvbm8ubXliYXRjaCIsImlhdCI6MTY2ODEyMjg0MSwiZXhwIjoxNjY4NzI3NjQxfQ.hiJwE9xea7TE8Gi5xH6BskBfY5PCpbdGRvHeuCe6xZg', 'sys', '2022-11-10 23:28:18', 'sys', '2022-11-10 23:28:18');
