drop table if exists MEMBER_INFO;
drop table if exists DESTINATION_INFO;
drop table if exists ORDER_INFO;
drop table if exists POSTAL_CODE_INFO;
drop table if exists SETTLEMENT_INFO;

CREATE TABLE `DESTINATION_INFO` (
  `LOGIN_ID` varchar(10) NOT NULL,
  `DESTINATION_INFO_LOGIN_BRANCH` int NOT NULL,
  `DESTINATION_EMAIL_ADDRESS` text NOT NULL,
  `DESTINATION_NAME` text NOT NULL,
  `DESTINATION_TEL_NO` text NOT NULL,
  `DESTINATION_POSTAL_CODE` text NOT NULL,
  `DESTINATION_PREFECTURE` text NOT NULL,
  `DESTINATION_CITY` text NOT NULL,
  `DESTINATION_TOWN` text NOT NULL,
  `DESTINATION_TOWN_NO` text NOT NULL,
  `DESTINATION_BUILDING` text,
  `DESTINATION_ROOM_NO` text,
  `PERSONAL_NAME` text NOT NULL,
  `PERSONAL_TEL_NO` text NOT NULL,
  `PERSONAL_POSTAL_CODE` text NOT NULL,
  `PERSONAL_PREFECTURE` text NOT NULL,
  `PERSONAL_CITY` text NOT NULL,
  `PERSONAL_TOWN` text NOT NULL,
  `PERSONAL_TOWN_NO` text NOT NULL,
  `PERSONAL_BUILDING` text,
  `PERSONAL_ROOM_NO` text,
  `CREATE_PRG` text NOT NULL,
  `CREATE_DATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_PRG` text NOT NULL,
  `UPDATE_DATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`LOGIN_ID`,`DESTINATION_INFO_LOGIN_BRANCH`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `DESTINATION_INFO` (`LOGIN_ID`, `DESTINATION_INFO_LOGIN_BRANCH`, `DESTINATION_EMAIL_ADDRESS`, `DESTINATION_NAME`, `DESTINATION_TEL_NO`, `DESTINATION_POSTAL_CODE`, `DESTINATION_PREFECTURE`, `DESTINATION_CITY`, `DESTINATION_TOWN`, `DESTINATION_TOWN_NO`, `DESTINATION_BUILDING`, `DESTINATION_ROOM_NO`, `PERSONAL_NAME`, `PERSONAL_TEL_NO`, `PERSONAL_POSTAL_CODE`, `PERSONAL_PREFECTURE`, `PERSONAL_CITY`, `PERSONAL_TOWN`, `PERSONAL_TOWN_NO`, `PERSONAL_BUILDING`, `PERSONAL_ROOM_NO`, `CREATE_PRG`, `CREATE_DATE_TIME`, `UPDATE_PRG`, `UPDATE_DATE_TIME`) VALUES
('L001', 1, 'tkysn1028@gmail.com', '苑　拓野', '08047388848', '1160014', '東京都', '荒川区', '東日暮里', '2-22-6', 'スカイハイム', '302', '苑　拓野', '08047388848', '1160014', '東京都', '荒川区', '東日暮里', '2-22-6', 'スカイハイム', '302', 'sys', '2022-11-19 04:48:18', 'sys', '2022-11-19 04:48:18');

CREATE TABLE `ORDER_INFO` (
  `LOGIN_ID` varchar(10) NOT NULL,
  `ORDER_INFO_LOGIN_BRANCH` int NOT NULL,
  `ORDER_INFO_LOGIN_BRANCH_DETAIL` int NOT NULL,
  `DESTINATION_INFO_LOGIN_BRANCH` int NOT NULL,
  `SETTLEMENT_INFO_LOGIN_BRANCH` int NOT NULL,
  `ITEM_ID` varchar(8) NOT NULL,
  `ITEM_PRICE_CONFIRM` int NOT NULL,
  `CREATE_PRG` text NOT NULL,
  `CREATE_DATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_PRG` text NOT NULL,
  `UPDATE_DATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`LOGIN_ID`,`ORDER_INFO_LOGIN_BRANCH`,`ORDER_INFO_LOGIN_BRANCH_DETAIL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `ORDER_INFO` (`LOGIN_ID`, `ORDER_INFO_LOGIN_BRANCH`, `ORDER_INFO_LOGIN_BRANCH_DETAIL`, `DESTINATION_INFO_LOGIN_BRANCH`, `SETTLEMENT_INFO_LOGIN_BRANCH`, `ITEM_ID`, `ITEM_PRICE_CONFIRM`, `CREATE_PRG`, `CREATE_DATE_TIME`, `UPDATE_PRG`, `UPDATE_DATE_TIME`) VALUES
('L001', 1, 1, 1, 1, 'i0000001', 500, 'sys', '2022-11-19 04:52:09', 'sys', '2022-11-19 04:52:09'),
('L001', 1, 2, 1, 1, 'i0000002', 600, 'sys', '2022-11-19 04:52:09', 'sys', '2022-11-19 04:52:09');


CREATE TABLE `ORDER_ITEM_INFO` (
  `LOGIN_ID` varchar(10) NOT NULL,
  `ORDER_ITEM_ID` varchar(8) NOT NULL,
  `ORDER_ITEM_PRICE` int NOT NULL,
  `DISCOUNT_DIV` varchar(4) NOT NULL,
  `DISCOUNT_MONEY` int DEFAULT NULL,
  `CREATE_PRG` text NOT NULL,
  `CREATE_DATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_DATE_TIME` text NOT NULL,
  `UPDATE_PRG` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`LOGIN_ID`,`ORDER_ITEM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `ORDER_ITEM_INFO` (`LOGIN_ID`, `ORDER_ITEM_ID`, `ORDER_ITEM_PRICE`, `DISCOUNT_DIV`, `DISCOUNT_MONEY`, `CREATE_PRG`, `CREATE_DATE_TIME`, `UPDATE_DATE_TIME`, `UPDATE_PRG`) VALUES
('L001', 'i0000001', 500, 'd000', 0, 'sys', '2022-11-19 04:51:07', 'sys', '2022-11-19 04:51:07'),
('L001', 'i0000002', 600, 'd000', 0, 'sys', '2022-11-19 04:51:07', 'sys', '2022-11-19 04:51:07');


CREATE TABLE `SETTLEMENT_INFO` (
  `LOGIN_ID` varchar(10) NOT NULL,
  `SETTLEMENT_INFO_LOGIN_BRANCH` int NOT NULL,
  `CARD_COMPANY_ID` varchar(10) NOT NULL,
  `CREDIT_CARD_NO` text NOT NULL,
  `SECURITY_CODE` text NOT NULL,
  `EXPIRE_DATE` text NOT NULL,
  `CREATE_PRG` text NOT NULL,
  `CREATE_DATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_PRG` text NOT NULL,
  `UPDATE_DATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`LOGIN_ID`,`SETTLEMENT_INFO_LOGIN_BRANCH`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `SETTLEMENT_INFO` (`LOGIN_ID`, `SETTLEMENT_INFO_LOGIN_BRANCH`, `CARD_COMPANY_ID`, `CREDIT_CARD_NO`, `SECURITY_CODE`, `EXPIRE_DATE`, `CREATE_PRG`, `CREATE_DATE_TIME`, `UPDATE_PRG`, `UPDATE_DATE_TIME`) VALUES
('L001', 1, 'C001', '000000000000000000000000', '000', '2023/04', 'sys', '2022-11-19 04:49:39', 'sys', '2022-11-19 04:49:39');
